// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Floor
{
    public int FloorId { get; set; }

    public string FloorName { get; set; }

    public int? DedicatedVehicleTypeId { get; set; }

    public int TotalCapacity { get; set; }

    public virtual VehicleType DedicatedVehicleType { get; set; }

    public virtual ICollection<Gate> Gates { get; set; } = new List<Gate>();

    public virtual ICollection<ParkingSlot> ParkingSlots { get; set; } = new List<ParkingSlot>();
}