// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Gate
{
    public int GateId { get; set; }

    public string GateName { get; set; }

    public string GateType { get; set; }

    public int FloorId { get; set; }

    public virtual Floor Floor { get; set; }

    public virtual ICollection<ParkingSession> ParkingSessionEntryGates { get; set; } = new List<ParkingSession>();

    public virtual ICollection<ParkingSession> ParkingSessionExitGates { get; set; } = new List<ParkingSession>();
}