// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class IncidentReport
{
    public Guid IncidentId { get; set; }

    public Guid? SessionId { get; set; }

    public Guid ReportedByUserId { get; set; }

    public string IssueType { get; set; }

    public string Description { get; set; }

    public string ProofImageUrl { get; set; }

    public string Status { get; set; }

    public Guid? HandledByStaffId { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public string ResolutionNotes { get; set; }

    public virtual User HandledByStaff { get; set; }

    public virtual User ReportedByUser { get; set; }

    public virtual ParkingSession Session { get; set; }
}