// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class MonthlySubscription
{
    public Guid SubscriptionId { get; set; }

    public Guid UserId { get; set; }

    public Guid VehicleTypeId { get; set; }

    public string LicensePlate { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public decimal Price { get; set; }

    public string Status { get; set; }

    public virtual User User { get; set; }

    public virtual VehicleType VehicleType { get; set; }
}