// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class ParkingSlot
{
    public long SlotId { get; set; }

    public int FloorId { get; set; }

    public string SlotCode { get; set; }

    public int VehicleTypeId { get; set; }

    public string Status { get; set; }

    public virtual Floor Floor { get; set; }

    public virtual ICollection<ParkingSession> ParkingSessionActualSlots { get; set; } = new List<ParkingSession>();

    public virtual ICollection<ParkingSession> ParkingSessionAssignedSlots { get; set; } = new List<ParkingSession>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual VehicleType VehicleType { get; set; }
}