// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class ParkingDBContext : DbContext
{
    public ParkingDBContext(DbContextOptions<ParkingDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Floor> Floors { get; set; }

    public virtual DbSet<Gate> Gates { get; set; }

    public virtual DbSet<IncidentReport> IncidentReports { get; set; }

    public virtual DbSet<ParkingCard> ParkingCards { get; set; }

    public virtual DbSet<ParkingSession> ParkingSessions { get; set; }

    public virtual DbSet<ParkingSlot> ParkingSlots { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PricingPolicy> PricingPolicies { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Reservation> Reservations { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<VehicleType> VehicleTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Floor>(entity =>
        {
            entity.HasKey(e => e.FloorId).HasName("PK__Floors__49D1E86B977ABAB9");

            entity.HasIndex(e => e.FloorName, "UQ__Floors__3D098F35BF898D02").IsUnique();

            entity.Property(e => e.FloorId).HasColumnName("FloorID");
            entity.Property(e => e.DedicatedVehicleTypeId).HasColumnName("DedicatedVehicleTypeID");
            entity.Property(e => e.FloorName)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.DedicatedVehicleType).WithMany(p => p.Floors)
                .HasForeignKey(d => d.DedicatedVehicleTypeId)
                .HasConstraintName("FK__Floors__Dedicate__3E52440B");
        });

        modelBuilder.Entity<Gate>(entity =>
        {
            entity.HasKey(e => e.GateId).HasName("PK__Gates__9582C630114151F9");

            entity.Property(e => e.GateId).HasColumnName("GateID");
            entity.Property(e => e.FloorId).HasColumnName("FloorID");
            entity.Property(e => e.GateName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.GateType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Floor).WithMany(p => p.Gates)
                .HasForeignKey(d => d.FloorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Gates__FloorID__5165187F");
        });

        modelBuilder.Entity<IncidentReport>(entity =>
        {
            entity.HasKey(e => e.IncidentId).HasName("PK__Incident__3D8053920D24A030");

            entity.Property(e => e.IncidentId).HasColumnName("IncidentID");
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.HandledByStaffId).HasColumnName("HandledByStaffID");
            entity.Property(e => e.IssueType)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProofImageUrl)
                .IsUnicode(false)
                .HasColumnName("ProofImageURL");
            entity.Property(e => e.ReportedByUserId).HasColumnName("ReportedByUserID");
            entity.Property(e => e.ResolvedAt).HasColumnType("datetime");
            entity.Property(e => e.SessionId).HasColumnName("SessionID");
            entity.Property(e => e.Status)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("Open");

            entity.HasOne(d => d.HandledByStaff).WithMany(p => p.IncidentReportHandledByStaffs)
                .HasForeignKey(d => d.HandledByStaffId)
                .HasConstraintName("FK__IncidentR__Handl__7A672E12");

            entity.HasOne(d => d.ReportedByUser).WithMany(p => p.IncidentReportReportedByUsers)
                .HasForeignKey(d => d.ReportedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__IncidentR__Repor__797309D9");

            entity.HasOne(d => d.Session).WithMany(p => p.IncidentReports)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK__IncidentR__Sessi__787EE5A0");
        });

        modelBuilder.Entity<ParkingCard>(entity =>
        {
            entity.HasKey(e => e.CardId).HasName("PK__ParkingC__55FECD8E9955E21F");

            entity.HasIndex(e => e.CardCode, "UQ__ParkingC__3D5317078E6D6ACE").IsUnique();

            entity.Property(e => e.CardId).HasColumnName("CardID");
            entity.Property(e => e.CardCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("Active");
        });

        modelBuilder.Entity<ParkingSession>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("PK__ParkingS__C9F492703B87944E");

            entity.Property(e => e.SessionId).HasColumnName("SessionID");
            entity.Property(e => e.ActualSlotId).HasColumnName("ActualSlotID");
            entity.Property(e => e.AssignedSlotId).HasColumnName("AssignedSlotID");
            entity.Property(e => e.CardId).HasColumnName("CardID");
            entity.Property(e => e.DriverUserId).HasColumnName("DriverUserID");
            entity.Property(e => e.EntryGateId).HasColumnName("EntryGateID");
            entity.Property(e => e.EntryImageUrl)
                .IsUnicode(false)
                .HasColumnName("EntryImageURL");
            entity.Property(e => e.EntryTime).HasColumnType("datetime");
            entity.Property(e => e.ExitGateId).HasColumnName("ExitGateID");
            entity.Property(e => e.ExitImageUrl)
                .IsUnicode(false)
                .HasColumnName("ExitImageURL");
            entity.Property(e => e.ExitTime).HasColumnType("datetime");
            entity.Property(e => e.LicensePlateIn)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.LicensePlateOut)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.ActualSlot).WithMany(p => p.ParkingSessionActualSlots)
                .HasForeignKey(d => d.ActualSlotId)
                .HasConstraintName("FK__ParkingSe__Actua__6E01572D");

            entity.HasOne(d => d.AssignedSlot).WithMany(p => p.ParkingSessionAssignedSlots)
                .HasForeignKey(d => d.AssignedSlotId)
                .HasConstraintName("FK__ParkingSe__Assig__6D0D32F4");

            entity.HasOne(d => d.Card).WithMany(p => p.ParkingSessions)
                .HasForeignKey(d => d.CardId)
                .HasConstraintName("FK__ParkingSe__CardI__68487DD7");

            entity.HasOne(d => d.DriverUser).WithMany(p => p.ParkingSessions)
                .HasForeignKey(d => d.DriverUserId)
                .HasConstraintName("FK__ParkingSe__Drive__693CA210");

            entity.HasOne(d => d.EntryGate).WithMany(p => p.ParkingSessionEntryGates)
                .HasForeignKey(d => d.EntryGateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ParkingSe__Entry__6B24EA82");

            entity.HasOne(d => d.ExitGate).WithMany(p => p.ParkingSessionExitGates)
                .HasForeignKey(d => d.ExitGateId)
                .HasConstraintName("FK__ParkingSe__ExitG__6C190EBB");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.ParkingSessions)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ParkingSe__Vehic__6A30C649");
        });

        modelBuilder.Entity<ParkingSlot>(entity =>
        {
            entity.HasKey(e => e.SlotId).HasName("PK__ParkingS__0A124A4FDCF57625");

            entity.HasIndex(e => e.SlotCode, "UQ__ParkingS__38BD98CC0C3270DA").IsUnique();

            entity.Property(e => e.SlotId).HasColumnName("SlotID");
            entity.Property(e => e.FloorId).HasColumnName("FloorID");
            entity.Property(e => e.SlotCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Available");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.Floor).WithMany(p => p.ParkingSlots)
                .HasForeignKey(d => d.FloorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ParkingSl__Floor__4CA06362");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.ParkingSlots)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ParkingSl__Vehic__4D94879B");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A58EAEA3665");

            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.Amount).HasColumnType("decimal(15, 2)");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("Success");
            entity.Property(e => e.PaymentTime).HasColumnType("datetime");
            entity.Property(e => e.ReservationId).HasColumnName("ReservationID");
            entity.Property(e => e.SessionId).HasColumnName("SessionID");
            entity.Property(e => e.TransactionReference)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Reservation).WithMany(p => p.Payments)
                .HasForeignKey(d => d.ReservationId)
                .HasConstraintName("FK__Payments__Reserv__73BA3083");

            entity.HasOne(d => d.Session).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payments__Sessio__72C60C4A");
        });

        modelBuilder.Entity<PricingPolicy>(entity =>
        {
            entity.HasKey(e => e.PolicyId).HasName("PK__PricingP__2E133944FABD33C4");

            entity.Property(e => e.PolicyId).HasColumnName("PolicyID");
            entity.Property(e => e.BasePrice).HasColumnType("decimal(15, 2)");
            entity.Property(e => e.EffectiveDate).HasColumnType("datetime");
            entity.Property(e => e.ExtraHourPrice).HasColumnType("decimal(15, 2)");
            entity.Property(e => e.NightSurcharge)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(15, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.PricingPolicies)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PricingPo__Vehic__5BE2A6F2");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.RefreshTokenId).HasName("PK__RefreshT__F5845E597785BB5E");

            entity.HasIndex(e => e.RefreshTokenKey, "UQ__RefreshT__08D6172DA1B335C3").IsUnique();

            entity.Property(e => e.RefreshTokenId).HasColumnName("RefreshTokenID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsRevoked).HasDefaultValue(false);
            entity.Property(e => e.RefreshTokenKey)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RefreshTo__UserI__18EBB532");
        });

        modelBuilder.Entity<Reservation>(entity =>
        {
            entity.HasKey(e => e.ReservationId).HasName("PK__Reservat__B7EE5F04BA0280E4");

            entity.Property(e => e.ReservationId).HasColumnName("ReservationID");
            entity.Property(e => e.AssignedSlotId).HasColumnName("AssignedSlotID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpectedEntryTime).HasColumnType("datetime");
            entity.Property(e => e.ExpectedExitTime).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("Pending");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.AssignedSlot).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.AssignedSlotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__Assig__6383C8BA");

            entity.HasOne(d => d.User).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__UserI__619B8048");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__Vehic__628FA481");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3A84D844E1");

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B6160DFD613DD").IsUnique();

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC54644625");

            entity.HasIndex(e => e.UserName, "UQ__Users__536C85E4AEC7DA38").IsUnique();

            entity.HasIndex(e => e.PhoneNumber, "UQ__Users__85FB4E38A7BB426F").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534FA1EAB94").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__RoleID__46E78A0C");
        });

        modelBuilder.Entity<VehicleType>(entity =>
        {
            entity.HasKey(e => e.VehicleTypeId).HasName("PK__VehicleT__9F44962374C085CE");

            entity.HasIndex(e => e.TypeName, "UQ__VehicleT__D4E7DFA8326D3181").IsUnique();

            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");
            entity.Property(e => e.Dimensions)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}