// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class ParkingSlot
{
    public Guid SlotId { get; set; }

    public Guid FloorId { get; set; }

    public string SlotCode { get; set; }

    public Guid VehicleTypeId { get; set; }

    public string Status { get; set; }

    public Guid? AssignedUserId { get; set; }

    public virtual User AssignedUser { get; set; }

    public virtual Floor Floor { get; set; }

    public virtual ICollection<ParkingSession> ParkingSessionActualSlots { get; set; } = new List<ParkingSession>();

    public virtual ICollection<ParkingSession> ParkingSessionAssignedSlots { get; set; } = new List<ParkingSession>();

    public virtual VehicleType VehicleType { get; set; }
}