// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class ParkingSession
{
    public Guid SessionId { get; set; }

    public Guid? ReservationId { get; set; }

    public Guid? CardId { get; set; }

    public Guid? DriverUserId { get; set; }

    public string LicensePlateIn { get; set; }

    public string LicensePlateOut { get; set; }

    public string EntryImageUrl { get; set; }

    public string ExitImageUrl { get; set; }

    public Guid VehicleTypeId { get; set; }

    public DateTime EntryTime { get; set; }

    public DateTime? ExitTime { get; set; }

    public Guid EntryGateId { get; set; }

    public Guid? ExitGateId { get; set; }

    public Guid? AssignedSlotId { get; set; }

    public Guid? ActualSlotId { get; set; }

    public string Status { get; set; }

    public virtual ParkingSlot ActualSlot { get; set; }

    public virtual ParkingSlot AssignedSlot { get; set; }

    public virtual ParkingCard Card { get; set; }

    public virtual User DriverUser { get; set; }

    public virtual Gate EntryGate { get; set; }

    public virtual Gate ExitGate { get; set; }

    public virtual ICollection<IncidentReport> IncidentReports { get; set; } = new List<IncidentReport>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Reservation Reservation { get; set; }

    public virtual VehicleType VehicleType { get; set; }
}