// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class ParkingDBContext : DbContext
{
    public ParkingDBContext(DbContextOptions<ParkingDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Floor> Floors { get; set; }

    public virtual DbSet<Gate> Gates { get; set; }

    public virtual DbSet<IncidentReport> IncidentReports { get; set; }

    public virtual DbSet<MonthlySubscription> MonthlySubscriptions { get; set; }

    public virtual DbSet<ParkingSession> ParkingSessions { get; set; }

    public virtual DbSet<ParkingSlot> ParkingSlots { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PricingPolicy> PricingPolicies { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Reservation> Reservations { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SubscriptionPackage> SubscriptionPackages { get; set; }

    public virtual DbSet<SubscriptionRenewal> SubscriptionRenewals { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<VehicleChangeRequest> VehicleChangeRequests { get; set; }

    public virtual DbSet<VehicleType> VehicleTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Floor>(entity =>
        {
            entity.HasKey(e => e.FloorId).HasName("PK__Floors__49D1E86B5EDE4231");

            entity.HasIndex(e => e.FloorName, "UQ__Floors__3D098F351BFDDF95").IsUnique();

            entity.Property(e => e.FloorId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("FloorID");
            entity.Property(e => e.DedicatedVehicleTypeId).HasColumnName("DedicatedVehicleTypeID");
            entity.Property(e => e.FloorName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.DedicatedVehicleType).WithMany(p => p.Floors)
                .HasForeignKey(d => d.DedicatedVehicleTypeId)
                .HasConstraintName("FK__Floors__Dedicate__4222D4EF");
        });

        modelBuilder.Entity<Gate>(entity =>
        {
            entity.HasKey(e => e.GateId).HasName("PK__Gates__9582C6308A4C273D");

            entity.Property(e => e.GateId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("GateID");
            entity.Property(e => e.FloorId).HasColumnName("FloorID");
            entity.Property(e => e.GateName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.GateType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Floor).WithMany(p => p.Gates)
                .HasForeignKey(d => d.FloorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Gates__FloorID__68487DD7");
        });

        modelBuilder.Entity<IncidentReport>(entity =>
        {
            entity.HasKey(e => e.IncidentId).HasName("PK__Incident__3D805392FC936773");

            entity.Property(e => e.IncidentId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("IncidentID");
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.HandledByStaffId).HasColumnName("HandledByStaffID");
            entity.Property(e => e.IssueType)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProofImageUrl)
                .IsUnicode(false)
                .HasColumnName("ProofImageURL");
            entity.Property(e => e.ReportedByUserId).HasColumnName("ReportedByUserID");
            entity.Property(e => e.ResolvedAt).HasColumnType("datetime");
            entity.Property(e => e.SessionId).HasColumnName("SessionID");
            entity.Property(e => e.Status)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("Open");

            entity.HasOne(d => d.HandledByStaff).WithMany(p => p.IncidentReportHandledByStaffs)
                .HasForeignKey(d => d.HandledByStaffId)
                .HasConstraintName("FK__IncidentR__Handl__1332DBDC");

            entity.HasOne(d => d.ReportedByUser).WithMany(p => p.IncidentReportReportedByUsers)
                .HasForeignKey(d => d.ReportedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__IncidentR__Repor__123EB7A3");

            entity.HasOne(d => d.Session).WithMany(p => p.IncidentReports)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK__IncidentR__Sessi__114A936A");
        });

        modelBuilder.Entity<MonthlySubscription>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId).HasName("PK__MonthlyS__9A2B24BDEC168A75");

            entity.Property(e => e.SubscriptionId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("SubscriptionID");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.FixedSlotId).HasColumnName("FixedSlotID");
            entity.Property(e => e.LicensePlate)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.Price).HasColumnType("decimal(15, 2)");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.FixedSlot).WithMany(p => p.MonthlySubscriptions)
                .HasForeignKey(d => d.FixedSlotId)
                .HasConstraintName("FK__MonthlySu__Fixed__6383C8BA");

            entity.HasOne(d => d.Package).WithMany(p => p.MonthlySubscriptions)
                .HasForeignKey(d => d.PackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MonthlySu__Packa__628FA481");

            entity.HasOne(d => d.User).WithMany(p => p.MonthlySubscriptions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MonthlySu__UserI__60A75C0F");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.MonthlySubscriptions)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MonthlySu__Vehic__619B8048");
        });

        modelBuilder.Entity<ParkingSession>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("PK__ParkingS__C9F49270D5D638BB");

            entity.Property(e => e.SessionId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("SessionID");
            entity.Property(e => e.ActualSlotId).HasColumnName("ActualSlotID");
            entity.Property(e => e.AssignedSlotId).HasColumnName("AssignedSlotID");
            entity.Property(e => e.DriverUserId).HasColumnName("DriverUserID");
            entity.Property(e => e.EntryGateId).HasColumnName("EntryGateID");
            entity.Property(e => e.EntryImageUrl)
                .IsUnicode(false)
                .HasColumnName("EntryImageURL");
            entity.Property(e => e.EntryTime).HasColumnType("datetime");
            entity.Property(e => e.ExitGateId).HasColumnName("ExitGateID");
            entity.Property(e => e.ExitImageUrl)
                .IsUnicode(false)
                .HasColumnName("ExitImageURL");
            entity.Property(e => e.ExitTime).HasColumnType("datetime");
            entity.Property(e => e.LicensePlateIn)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.LicensePlateOut)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.ActualSlot).WithMany(p => p.ParkingSessionActualSlots)
                .HasForeignKey(d => d.ActualSlotId)
                .HasConstraintName("FK__ParkingSe__Actua__02084FDA");

            entity.HasOne(d => d.AssignedSlot).WithMany(p => p.ParkingSessionAssignedSlots)
                .HasForeignKey(d => d.AssignedSlotId)
                .HasConstraintName("FK__ParkingSe__Assig__01142BA1");

            entity.HasOne(d => d.DriverUser).WithMany(p => p.ParkingSessions)
                .HasForeignKey(d => d.DriverUserId)
                .HasConstraintName("FK__ParkingSe__Drive__7D439ABD");

            entity.HasOne(d => d.EntryGate).WithMany(p => p.ParkingSessionEntryGates)
                .HasForeignKey(d => d.EntryGateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ParkingSe__Entry__7F2BE32F");

            entity.HasOne(d => d.ExitGate).WithMany(p => p.ParkingSessionExitGates)
                .HasForeignKey(d => d.ExitGateId)
                .HasConstraintName("FK__ParkingSe__ExitG__00200768");

            entity.HasOne(d => d.Reservation).WithMany(p => p.ParkingSessions)
                .HasForeignKey(d => d.ReservationId)
                .HasConstraintName("FK__ParkingSe__Reser__7C4F7684");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.ParkingSessions)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ParkingSe__Vehic__7E37BEF6");
        });

        modelBuilder.Entity<ParkingSlot>(entity =>
        {
            entity.HasKey(e => e.SlotId).HasName("PK__ParkingS__0A124A4FA9AB625E");

            entity.HasIndex(e => e.SlotCode, "UQ__ParkingS__38BD98CC61B18F3D").IsUnique();

            entity.Property(e => e.SlotId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("SlotID");
            entity.Property(e => e.AssignedUserId).HasColumnName("AssignedUserID");
            entity.Property(e => e.FloorId).HasColumnName("FloorID");
            entity.Property(e => e.SlotCode)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Available");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.AssignedUser).WithMany(p => p.ParkingSlots)
                .HasForeignKey(d => d.AssignedUserId)
                .HasConstraintName("FK__ParkingSl__Assig__5AEE82B9");

            entity.HasOne(d => d.Floor).WithMany(p => p.ParkingSlots)
                .HasForeignKey(d => d.FloorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ParkingSl__Floor__59063A47");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.ParkingSlots)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ParkingSl__Vehic__59FA5E80");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A5885E45647");

            entity.Property(e => e.PaymentId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("PaymentID");
            entity.Property(e => e.Amount).HasColumnType("decimal(15, 2)");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("Pending");
            entity.Property(e => e.PaymentTime).HasColumnType("datetime");
            entity.Property(e => e.PaymentType)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.ReservationId).HasColumnName("ReservationID");
            entity.Property(e => e.SessionId).HasColumnName("SessionID");
            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");
            entity.Property(e => e.TransactionReference)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Reservation).WithMany(p => p.Payments)
                .HasForeignKey(d => d.ReservationId)
                .HasConstraintName("FK__Payments__Reserv__0A9D95DB");

            entity.HasOne(d => d.Session).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK__Payments__Sessio__09A971A2");

            entity.HasOne(d => d.Subscription).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SubscriptionId)
                .HasConstraintName("FK__Payments__Subscr__0B91BA14");

            entity.HasOne(d => d.User).WithMany(p => p.Payments)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Payments__UserID__08B54D69");
        });

        modelBuilder.Entity<PricingPolicy>(entity =>
        {
            entity.HasKey(e => e.PolicyId).HasName("PK__PricingP__2E133944BE384E7F");

            entity.Property(e => e.PolicyId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("PolicyID");
            entity.Property(e => e.BasePrice).HasColumnType("decimal(15, 2)");
            entity.Property(e => e.EffectiveDate).HasColumnType("datetime");
            entity.Property(e => e.ExtraHourPrice).HasColumnType("decimal(15, 2)");
            entity.Property(e => e.NightSurcharge)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(15, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.PricingPolicies)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PricingPo__Vehic__6EF57B66");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.RefreshTokenId).HasName("PK__RefreshT__F5845E59D238F276");

            entity.HasIndex(e => e.RefreshTokenKey, "UQ__RefreshT__08D6172D15A669E1").IsUnique();

            entity.Property(e => e.RefreshTokenId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("RefreshTokenID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsRevoked).HasDefaultValue(false);
            entity.Property(e => e.RefreshTokenKey)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RefreshTo__UserI__19DFD96B");
        });

        modelBuilder.Entity<Reservation>(entity =>
        {
            entity.HasKey(e => e.ReservationId).HasName("PK__Reservat__B7EE5F04C28482FA");

            entity.Property(e => e.ReservationId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ReservationID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpectedEntryTime).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("Pending");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.User).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__UserI__75A278F5");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__Vehic__76969D2E");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3A17A2FE02");

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B6160DB06DF77").IsUnique();

            entity.Property(e => e.RoleId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("RoleID");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SubscriptionPackage>(entity =>
        {
            entity.HasKey(e => e.PackageId).HasName("PK__Subscrip__322035EC730E687F");

            entity.Property(e => e.PackageId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("PackageID");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.PackageName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(15, 2)");
            entity.Property(e => e.RequireFixedSlot).HasDefaultValue(false);
            entity.Property(e => e.Status)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.SubscriptionPackages)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Subscript__Vehic__52593CB8");
        });

        modelBuilder.Entity<SubscriptionRenewal>(entity =>
        {
            entity.HasKey(e => e.RenewalId).HasName("PK__Subscrip__AF5B6A21735A422B");

            entity.Property(e => e.RenewalId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("RenewalID");
            entity.Property(e => e.Amount).HasColumnType("decimal(15, 2)");
            entity.Property(e => e.NewEndDate).HasColumnType("datetime");
            entity.Property(e => e.OldEndDate).HasColumnType("datetime");
            entity.Property(e => e.RenewalDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");

            entity.HasOne(d => d.Subscription).WithMany(p => p.SubscriptionRenewals)
                .HasForeignKey(d => d.SubscriptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Subscript__Subsc__2645B050");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACAE8A7B8C");

            entity.HasIndex(e => e.PhoneNumber, "UQ__Users__85FB4E387ECD8862").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534533289F1").IsUnique();

            entity.HasIndex(e => e.UserName, "UQ__Users__C9F28456E2A25A48").IsUnique();

            entity.Property(e => e.UserId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("UserID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__RoleID__4BAC3F29");
        });

        modelBuilder.Entity<VehicleChangeRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__VehicleC__33A8519AB30E602C");

            entity.Property(e => e.RequestId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("RequestID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.HandledByStaffId).HasColumnName("HandledByStaffID");
            entity.Property(e => e.NewLicensePlate)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.OldLicensePlate)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.ProcessedAt).HasColumnType("datetime");
            entity.Property(e => e.Reason).HasMaxLength(500);
            entity.Property(e => e.Status)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("Pending");
            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");

            entity.HasOne(d => d.HandledByStaff).WithMany(p => p.VehicleChangeRequests)
                .HasForeignKey(d => d.HandledByStaffId)
                .HasConstraintName("FK__VehicleCh__Handl__2180FB33");

            entity.HasOne(d => d.Subscription).WithMany(p => p.VehicleChangeRequests)
                .HasForeignKey(d => d.SubscriptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VehicleCh__Subsc__208CD6FA");
        });

        modelBuilder.Entity<VehicleType>(entity =>
        {
            entity.HasKey(e => e.VehicleTypeId).HasName("PK__VehicleT__9F44962373F1660D");

            entity.HasIndex(e => e.TypeName, "UQ__VehicleT__D4E7DFA804867992").IsUnique();

            entity.Property(e => e.VehicleTypeId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("VehicleTypeID");
            entity.Property(e => e.Dimensions)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}