// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Payment
{
    public long PaymentId { get; set; }

    public long SessionId { get; set; }

    public long? ReservationId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime PaymentTime { get; set; }

    public string PaymentStatus { get; set; }

    public string TransactionReference { get; set; }

    public virtual Reservation Reservation { get; set; }

    public virtual ParkingSession Session { get; set; }
}