// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Payment
{
    public Guid PaymentId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? SessionId { get; set; }

    public Guid? ReservationId { get; set; }

    public Guid? SubscriptionId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentType { get; set; }

    public DateTime PaymentTime { get; set; }

    public string PaymentStatus { get; set; }

    public string TransactionReference { get; set; }

    public virtual Reservation Reservation { get; set; }

    public virtual ParkingSession Session { get; set; }

    public virtual MonthlySubscription Subscription { get; set; }

    public virtual User User { get; set; }
}