// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class PricingPolicy
{
    public Guid PolicyId { get; set; }

    public Guid VehicleTypeId { get; set; }

    public decimal BasePrice { get; set; }

    public int BaseHours { get; set; }

    public decimal ExtraHourPrice { get; set; }

    public decimal? NightSurcharge { get; set; }

    public DateTime EffectiveDate { get; set; }

    public string Status { get; set; }

    public virtual VehicleType VehicleType { get; set; }
}