// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Reservation
{
    public long ReservationId { get; set; }

    public long UserId { get; set; }

    public int VehicleTypeId { get; set; }

    public long AssignedSlotId { get; set; }

    public DateTime ExpectedEntryTime { get; set; }

    public DateTime ExpectedExitTime { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ParkingSlot AssignedSlot { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }

    public virtual VehicleType VehicleType { get; set; }
}