// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class SubscriptionPackage
{
    public Guid PackageId { get; set; }

    public string PackageName { get; set; }

    public Guid VehicleTypeId { get; set; }

    public int DurationMonths { get; set; }

    public decimal Price { get; set; }

    public bool? RequireFixedSlot { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual ICollection<MonthlySubscription> MonthlySubscriptions { get; set; } = new List<MonthlySubscription>();

    public virtual VehicleType VehicleType { get; set; }
}