// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class SubscriptionRenewal
{
    public Guid RenewalId { get; set; }

    public Guid SubscriptionId { get; set; }

    public DateTime OldEndDate { get; set; }

    public DateTime NewEndDate { get; set; }

    public decimal Amount { get; set; }

    public DateTime? RenewalDate { get; set; }

    public virtual MonthlySubscription Subscription { get; set; }
}