// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class VehicleChangeRequest
{
    public Guid RequestId { get; set; }

    public Guid SubscriptionId { get; set; }

    public string OldLicensePlate { get; set; }

    public string NewLicensePlate { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public Guid? HandledByStaffId { get; set; }

    public virtual User HandledByStaff { get; set; }

    public virtual MonthlySubscription Subscription { get; set; }
}